In [2]:
import pandas as pd

# Задание 1
Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:

    если источник traffic_source равен yandex или google, то в source_type ставится organic
    для источников paid и email из России - ставим ad
    для источников paid и email не из России - ставим other
    все остальные варианты берем из traffic_source без изменений

In [26]:
log = pd.read_csv('visit_log.csv', sep=';')
log.tail()

,timestamp,visit_id,url,region,user_id,traffic_source
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email

In [28]:
log.loc[log.traffic_source.isin(['yandex', 'google']), 'source_type'] = 'organic'
log.loc[(log.traffic_source.isin(['paid', 'email']))&(log.region == 'Russia'), 'source_type'] = 'ad'
log.loc[(log.traffic_source.isin(['paid', 'email']))&(log.region != 'Russia'), 'source_type'] = 'other'
log.loc[pd.isna(log.source_type), 'source_type'] = log.traffic_source
log.tail(10)

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
18928,1550094255,c7e4bce62a,https://host.ru/8880fd00cf23066541,Australia,e721d23ec6,yandex,organic
18929,1550094260,39aeec73f8,https://host.ru/ee7c4e0674a284ee3f,Russia,9c832cf9d4,direct,NaN
18930,1550094269,f1b4590410,https://host.ru/a5dda93e70318570c0,Russia,7f59a1e6a7,direct,NaN
18931,1550094269,a7e2dfd759,https://host.ru/ef57543002ce2a0f2a,Belarus,04fec64cda,direct,NaN
18932,1550094280,5001544772,https://host.ru/9f90e5c423a5f976d4,Russia,072148e3ba,google,organic
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid,other
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid,ad
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex,organic
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid,ad
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,ad

# Задание 2
В файле URLs.txt содержатся url страниц новостного сайта. Вам необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. Выполните следующие действия:

    Прочитайте содержимое файла с датафрейм
    Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии с заданным шаблоном

In [30]:
with open('URLs.txt') as f:
    table = [ x.strip().split('\t') for x in f.readlines()]
table

[['url'],
 ['/world/'],
 ['/latest/'],
 ['/?updated=top'],
 ['/politics/36188461-s-marta-zhizn-rossiyan-suschestvenno-izmenitsya-iz-za-novyh-zakonov/'],
 ['/world/36007585-tramp-pridumal-kak-reshit-ukrainskiy-vopros/'],
 ['/science/36157853-nasa-sobiraet-ekstrennuyu-press-konferentsiyu-na-temu-vnezemnoy-zhizni/'],
 ['/video/36001498-poyavilis-pervye-podrobnosti-gibeli-natali-melamed/'],
 ['/world/36007585-tramp-pridumal-kak-reshit-ukrainskiy-vopros/?smi2=1'],
 ['/science/'],
 ['/sport/'],
 ['/middleeast/36131117-divizion-s-400-ne-zametil-ataki-f-35-pod-damaskom/'],
 ['/economics/36065674-rossiyane-vozmutilis-minimalnymi-zarplatami-v-stranah-es/'],
 ['/politics/36118047-otets-24-detey-potreboval-izvineniy-ot-soloveva/?smi2=1'],
 ['/travel/36194479-v-sheremetevo-passazhiry-ustroili-bunt/'],
 ['/politics/35638742-nesolidno-mariya-zaharova-sdelala-neozhidannoe-priznanie/'],
 ['/video/36012692-tramp-otkrestilsya-ot-rossii-i-putina/'],
 ['/starlife/36174817-guzeeva-rasstalas-s-muzhem/'],
 ['/health/36149308-predlozheno-prostoe-sredstvo-ot-insulta/'],
 ['/science/36139723-set-vzbudorazhila-novost-o-sensatsii-nasa/'],
 ['/cis/36229699-poroshenko-obyavil-vseukrainskiy-traur/'],
 ['/incidents/36225203-tonnel-obrushilsya-v-novoy-moskve-pod-zavalami-lyudi/'],
 ['/politics/36118047-otets-24-detey-potreboval-izvineniy-ot-soloveva/'],
 ['/world/36075956-na-granitse-s-krymom-zahvachena-baza-krymsko-tatarskogo-batalona/'],
 ['/politics/36115220-mid-vystupil-s-preduprezhdeniem-k-rossiyanam/'],
 ['/world/36018565-sbu-opublikovala-zapis-peregovorov-plotnitskogo-o-sbitom-il-76/'],
 ['/politics/36150505-stala-izvestna-prichina-smerti-churkina/'],
 ['/middleeast/36131117-divizion-s-400-ne-zametil-ataki-f-35-pod-damaskom/?smi2=1'],
 ['/sport/36055585-fiyon-maye-my-prouchili-russkih-moshennikov-na-trasse/'],
 ['/crazy-world/36193471-seks-bezhentsy-vernulis-v-germaniyu-iz-novosibirskoy-glubinki/'],
 ['/crazy-world/36087352-moskvicha-shokirovala-nahodka-v-steyke/'],
 ['/incidents/36096689-rossiyskih-turistov-dvazhdy-zakidali-kamnyami-v-abhazii/'],
 ['/video/36225009-otschet-poshel-zaharchenko-nazval-srok-likvidatsii-ukrainy/'],
 ['/auto/'],
 ['/health/36139780-opredelen-reshayuschiy-faktor-zdorovya-zubov/'],
 ['/scitech/'],
 ['/business/36187789-v-rf-hotyat-povysit-nalogi-dlya-obychnyh-grazhdan/'],
 ['/video/35930625-dozvonivshiysya-v-efir-ukrainskogo-tv-rasskazal-o-zhizni-v-krymu/?smi2=1'],
 ['/lifestyle/'],
 ['/head/36214416-u-zheny-karachentsova-nashli-alkogol-v-krovi/'],
 ['/latest/?page=1'],
 ['/head/36038043-foto-otdyhayuschiy-obama-vzbudorazhil-set/slides/'],
 ['/cis/36189830-kiev-arestoval-imuschestvo-v-krymu/'],
 ['/video/36006794-pogibshaya-melamed-ostavila-predsmertnuyu-zapisku/'],
 ['/video/36082961-nikol-kidman-prishla-na-britanskiy-oskar-v-neprilichnom-plate/'],
 ['/incidents/36173928-v-ekaterinburge-migranty-ustroili-bunt/'],
 ['/video/36151719-petrosyanu-grozit-sud/'],
 ['/business/36102731-rubl-rezko-otreagiroval-na-soobscheniya-o-vstreche-putina-s-oreshkinym/'],
 ['/articles/36193368-donbass-reshil-udarit-pervym/'],
 ['/science/36178249-rasshifrovano-predskazanie-nostradamusa-na-2017-god/'],
 ['/world/36206871-na-ukraine-nachalsya-shturm-uchastnikov-blokady-donbassa/'],
 ['/science/36233829-sozdano-lekarstvo-ot-vseh-vidov-raka/'],
 ['/politics/36093799-sbezhavshuyu-iz-rossii-maksakovu-uvolili-iz-gnesinki/'],
 ['/cis/36144647-v-tsentr-kieva-styagivayut-voennuyu-tehniku/'],
 ['/starlife/36140271-skandalnoe-foto-britni-spirs-vzorvalo-instagram/'],
 ['/finances/36043911-rublyu-predrekli-dvoynoy-udar/'],
 ['/starlife/36135554-doch-valerii-snyalas-v-otkrovennoy-fotosessii/'],
 ['/starlife/36005664-dzhennifer-lopes-vzorvala-internet-intimnym-foto/'],
 ['/starlife/36240935-dzhigurde-postavili-diagnoz/'],
 ['/politics/36233197-times-britaniya-peregnula-palku-s-krymom/'],
 ['/articles/36213214-vozmozhna-bolshaya-voyna/'],
 ['/articles/36142564-ukrainu-ureguliruyut-po-tihomu/'],
 ['/starlife/36044627-u-malyshevoy-sdali-nervy-na-peredache/'],
 ['/starlife/36053306-dzhigarhanyan-dal-shokiruyuschee-intervyu-o-byvshih-zhenah/'],
 ['/business/36184872-udar-po-schetchiku-rossiyane-stolknulis-s-dikim-skachkom-tarifov-zhkh/'],
 ['/world/36195262-deputat-savchenko-predlozhila-ukraintsam-posledovat-za-krymom/'],
 ['/starlife/36014715-evelina-bledans-vyshla-v-svet-bez-nizhnego-belya/'],
 ['/europe/36046038-v-parizhskom-metro-progremel-vzryv/'],
 ['/middleeast/36024757-v-sekretnoy-tyurme-v-sirii-povesheny-13-tysyach-chelovek/'],
 ['/video/36202662-nakazanie-dlya-lukashenko-rossiya-nashla-zhestkiy-rychag-protiv-belorussii/'],
 ['/articles/36170146-rossiya-reshila-postavlyat-ugol-napryamuyu-v-donbass/'],
 ['/business/36016781-sberbank-cib-nazval-sroki-devalvatsii-rublya/'],
 ['/politics/36229424-rossiya-vyrazila-protest-bolgarii/'],
 ['/kinomusic/36016432-igorya-krutogo-prooperirovali-v-amerike/'],
 ['/starlife/36008814-minus-odin-nyusha-otkazalas-ehat-v-kiev-na-evrovidenie/'],
 ['/lifestyle/36185060-uchenye-rasskazali-kak-v-buduschem-izmenitsya-seks/'],
 ['/articles/36082911-pribaltika-i-ukraina-v-panike-ili-igla-byvaet-ne-tolko-neftyanaya/'],
 ['/politics/36203629-v-gosdume-obyasnili-perenos-dnya-zaschitnika-otechestva/'],
 ['/economics/36097033-a-zhit-za-schet-rossii-vy-gotovy/?smi2=1'],
 ['/incidents/36003455-natalya-melamed-pered-gibelyu-prozhila-v-lesu-dva-dnya/'],
 ['/starlife/36131560-maksakova-shokirovala-otkrovennymi-fotografiyami/'],
 ['/sport/36235520-v-britanii-razgorelsya-krupneyshiy-doping-skandal-v-istorii/'],
 ['/articles/36093326-shturmovat-donetsk-i-lugansk-budut-pidzhaki/'],
 ['/video/36214784-panayotov-sdelal-shokiruyuschee-priznanie/'],
 ['/world/36215106-lider-ig-obratilsya-k-boevikam-s-proschalnoy-rechyu/'],
 ['/articles/36066499-iz-za-zvaniy-anny-netrebko-i-zary-razgorelis-skandaly/'],
 ['/starlife/36096316-u-lyudmily-maksakovoy-sdali-nervy-posle-pobega-docheri-na-ukrainu/?24smi=1'],
 ['/economics/36097033-a-zhit-za-schet-rossii-vy-gotovy/'],
 ['/starlife/36096182-vdova-valeriya-zolotuhina-vstretila-novuyu-lyubov/'],
 ['/cis/35984145-kreml-prokommentiroval-soobscheniya-smi-o-vozmozhnom-razvale-eaes-iz-za-belorussii/?24smi=1'],
 ['/video/36071019-olimpiyskie-obekty-rio-prevratilis-v-ruiny/'],
 ['/science/36151301-nazvano-posledstvie-zloupotrebleniya-alkogolem/'],
 ['/incidents/36027330-vospitatelnitsu-zatravili-za-erotichnoe-foto-s-vedrom/'],
 ['/world/36103095-dominikanskih-zhurnalistov-ubili-v-pryamom-efire/']]

In [33]:
df = pd.DataFrame(table[1:], columns= table[0])
df.head()

                                                 url
0                                            /world/
1                                           /latest/
2                                      /?updated=top
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...

In [40]:
df[df.url.str.contains('/\d{8}-', regex=True)]

                                                  url
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
88  /cis/35984145-kreml-prokommentiroval-soobschen...
89  /video/36071019-olimpiyskie-obekty-rio-prevrat...
90  /science/36151301-nazvano-posledstvie-zloupotr...
91  /incidents/36027330-vospitatelnitsu-zatravili-...
92  /world/36103095-dominikanskih-zhurnalistov-ubi...

[84 rows x 1 columns]

# Домашнее задание 3

В датафрейме data создайте столбец lemmas, в котором вычислите леммы поисковых запросов из столбца keyword. Леммы должны иметь строковый тип.

In [3]:
data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})
data

                 keyword   shows
0    курс гривны к рублю  125076
1        доллары в рубли  114173
2  100 долларов в рублях   97534
3             курс рубля   53546

In [10]:
from pymystem3 import Mystem
data['lemmas'] = data.keyword.apply(lambda x: ' '.join(Mystem().lemmatize(x)[:-1]))
data.head()

                 keyword   shows                     lemmas
0    курс гривны к рублю  125076  курс   гривна   к   рубль
1        доллары в рубли  114173         доллар   в   рубль
2  100 долларов в рублях   97534   100   доллар   в   рубль
3             курс рубля   53546               курс   рубль